project:
  type: book
  output-dir: ../docs

book:
  title: "Characterization of Intertidal Vegetation on European Coasts Using Multi-Scale Remote Sensing in Response to Natural and Anthropogenic Pressures"
  author: 
    name: Simon Oiry
    url: https://oirysimon.com
  date: "March 11, 2025"
  downloads: [pdf, docx]
  abstract: "To Be Written"
  chapters:
    - index.qmd
    - Intro/intro.qmd
    - Summary/summary.qmd
    - References/references.qmd
    
repo-url: https://github.com/SigOiry/PhD
search: true

thesis:
  supervisors:
    - name: Prof. Laurent Barillé
    - name: Dr. Pierre Gernez
  university: University of Nantes
  department: "Institut Des Substances et Organismes de la Mer laboratory"
  group: "Remote Sensing, Benthic Ecology and Ecotoxicology team"
  degree-name: "Doctor of Philosophy in Marine Ecology"
  faculty: Sciences & Techniques
  logoED: images/Logos_vaame_PdL.png
  logoED-height: "1.5cm"
  logoUN: images/Logotype_Nantes-U_noir-300dpi.png
  logoUN-height: "1cm"
  
  
bibliography: References/references.bib

format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
  html:
    theme: cosmo
  quarto-thesis-docx: default

editor: source

