project:
  type: book
  output-dir: ../docs
book:
  title: "Characterization of Intertidal Vegetation on European Coasts Using Multi-Scale Remote Sensing in Response to Natural and Anthropogenic Pressures"
  author: 
    name: Simon Oiry
    url: https://oirysimon.com
  date: "March 11, 2025"
  downloads: [pdf, docx]
  abstract: "To Be Written"
  search: true
  chapters:
    - index.qmd
    - Chapter1/intro.qmd
    - Chapter2/Chapter2.qmd
    - Chapter3/Chapter3.qmd
    - Summary/summary.qmd
    - References/references.qmd
repo-url: https://github.com/SigOiry/PhD
search: true
thesis:
  supervisors:
    - name: Prof. Laurent Barillé
    - name: Dr. Pierre Gernez
  university: University of Nantes
  department: "Institut Des Substances et Organismes de la Mer laboratory"
  group: "Remote Sensing, Benthic Ecology and Ecotoxicology team"
  degree-name: "Doctor of Philosophy in Marine Ecology"
  faculty: Sciences & Techniques
  logoED: images/Logos_vaame_PdL.png
  logoED-height: "1.5cm"
  logoUN: images/Logotype_Nantes-U_noir-300dpi.png
  logoUN-height: "1cm"
  
  
bibliography: [References/Introduction.bib, References/Chapiter2.bib, References/Chapiter3.bib, References/packages.bib] 
csl: RSE.csl

format:
  quarto-thesis-pdf: 
    urlcolor: black
    toclinkcolor: black
    toc-depth: 5
    titlepage: true
    latex-options: 
      - margin=1in
    include-in-header: chaptertitlepage.tex
    output-file: "PhD_Simon"
  quarto-thesis-html:
    theme: cosmo
  docx: 
    output-file: "PhD_Simon"
    reference-doc: quarto_template.docx

editor: source

