project:
  type: book
  output-dir: ../docs

book:
  title: "Characterization of Intertidal Vegetation on European Coasts Using Multi-Scale Remote Sensing in Response to Natural and Anthropogenic Pressures"
  author: 
    name: Simon Oiry
    url: https://oirysimon.com
  date: "March 15, 2025"
  downloads: [pdf, docx]
  abstract: "To Be Written"
  chapters:
    - index.qmd
    - Intro/intro.qmd
    - Summary/summary.qmd
    - References/references.qmd
    
repo-url: https://github.com/nmfs-opensci/quarto-thesis
search: true

thesis:
  supervisors:
    - name: Prof. Laurent Barillé
    - name: Dr. Pierre Gernez
  university: University of Nantes
  department: "Institut Des Substances et Organismes de la Mer (ISOMer)"
  group: "Remote Sensing, Benthic Ecology and Ecotoxicology (RSBE²)"
  faculty: Sciences & Techniques
bibliography: References/references.bib

format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
  quarto-thesis-html:
    theme: cosmo
  quarto-thesis-docx: default

editor: source

