---
title: Introduction & Overview
---

```{=latex}
\begin{spacing}{1.5}
```
## General Introduction 
### Coastal Environment 
### Remote sensing applied to Coastal environments 

Remote sensing (RS) defines the ability to retrieve information in a non-invasive way, without direct contact with the target. It relies on the propagation of signals, typically optical, acoustic, or microwave, between the target and the sensor. This technology is applied in a wide variety of fields, ranging from medical imaging to detect stem cells, to the analysis of the structure of the primordial universe [@zhu2021deep ; @aghanim2020resultats]. Remote sensing is integral to Earth observation (EO), where its methodologies facilitate large-scale and long-term data collection. Instruments on satellites, aircraft, and drones provide high-resolution imagery and measurements critical for monitoring environmental changes, mapping natural resources, and assessing land use patterns. These technologies enable systematic data collection over large areas and extended periods, supporting analyses such as deforestation, glacial melting, variations in ocean temperature, and land use mapping.

Coastal environments represent highly dynamic and sensitive ecosystems shaped by complex interactions between natural processes and human activities. Remote sensing technologies are crucial for monitoring these regions, providing detailed data on shoreline erosion, habitat degradation, sediment dynamics, and water quality. High-resolution satellite imagery and drone-based platforms facilitate the detection of fine-scale changes in intertidal zones, mangroves, coral reefs, and other critical coastal habitats. These observations enable the quantification of spatial and temporal variations, informing evidence-based strategies for conservation and sustainable management. 

The following sections examine two complementary approaches within the field of remote sensing for Earth observation: active and passive remote sensing. Through examples focused on coastal monitoring, these sections will introduce the remote sensing methodologies employed in this work while outlining their respective advantages and challenges.

#### Active Remote Sensing, Exemple of the LiDAR

Active remote sensing is a technique in which a sensor emits its own energy—typically in the form of electromagnetic radiation—toward a target and measures the energy reflected or backscattered from that target. This method allows for the collection of data regardless of natural light conditions, enabling observations during both day and night and through various weather conditions. 

LiDAR, which stands for Light Detection and Ranging, uses laser light to measure distances to objects or surfaces. By emitting laser pulses and measuring the time it takes for them to reflect back from a target, LiDAR systems can create precise, three-dimensional representations of the environment.

LiDAR works by emitting a beam of light and measuring the time it takes for the beam to return to the sensor. This process not only calculates distance but can also capture the intensity of the returned signal. In many instances, multiple returns from a single pulse are measured, which allows for mapping the different heights of objects within the same x and y coordinates. This capability is particularly useful for applications such as mapping the heights of trees in a forest or measuring crop heights in agricultural fields. When the height of the ground cannot be measured, LiDAR data can only generate a digital surface model (DSM), which represents the topmost layer of the environment. However, if multiple returns are recorded, it becomes possible to create both a DSM and a digital terrain model (DTM), which represents the ground surface, by differentiating between surface and underlying layers. The difference between DSM and DTM can be uses to assess living stock or biomass.
Achieving accuracy in LiDAR measurements is essential due to the high speed of light, approximately 300,000 km/s. Each step of the process, including the precise timing of the beam's return and the accurate positioning of the sensor (typically mounted on a drone, aircraft, or satellite), must be meticulously calibrated. The use of Real-Time Kinematic (RTK) positioning ensures that the sensor’s x, y, and z coordinates are known with high precision at all times. Without these measures, the resulting data may produce a distorted and noisy representation of the mapped surface, rendering it unreliable for analysis. 

In coastal environment monitoring, LiDAR systems are distinguished by their emitted wavelengths, which dictate their performance and application. These systems are categorized into "topographic LiDAR" and "bathymetric LiDAR," each suited to specific tasks in coastal studies. Topographic LiDAR operates in the near-infrared spectrum (approximately 1000 nm), excelling at mapping terrestrial features such as beach contours, vegetation density, and man-made structures. Its ability to generate high-density point clouds stems from efficient operation at lower power, though its utility is restricted to emerged surfaces due to the absorption of infrared light in water. Conversely, bathymetric LiDAR, utilizing green wavelengths (~532 nm), penetrates water to reveal submerged landscapes, including coral reefs, seagrass meadows, and shallow seabeds. While this capability is indispensable for underwater mapping, its effectiveness on land is hindered by atmospheric scattering. Together, these technologies provide complementary tools for comprehensive coastal assessments, enabling precise data collection tailored to both terrestrial and aquatic environments. 

- In the present study we used only IR lidar because intertidal flat are flat with few to none 3D structure. and we operate at low tide.

#### Passive Remote Sensing

- Sun is used as a light source of energy most of the time but not evry time (SST measurement for example)

- reflectance, absorbance, transmitance

- Spectral signature, abosorption of pigments -> derivative

## Overview 

Discriminating green macroalgae from seagrasses throught remote sensing poses significant challenges due to their overlapping spectral signatures and similar pigment compositions, particularly in the visible and near-infrared spectral regions. Both vegetation types share key pigments such as chlorophyll-a and carotenoids, which lead to analogous reflectance patterns. This similarity complicates their differentiation using conventional remote sensing techniques, especially when these species coexist within heterogeneous habitats. Despite these challenges, advances in spectral resolution and machine learning provide avenues for improved classification.

Chapter 2 establishes the foundation by presenting a proof-of-concept study that demonstrates the feasibility of discriminating green macroalgae from seagrasses in intertidal zones using remote sensing. By employing both multi- and hyperspectral datasets, the study elucidates the specific wavelengths and spectral resolutions that maximize classification accuracy, showcasing the potential of remote sensing for detailed habitat mapping.

Building upon the proof of concept, Chapter 3 focuses on the development of a robust algorithm capable of automating the discrimination of green macrophytes in heterogeneous intertidal habitats. Utilizing high-resolution multispectral drone imagery and advanced machine learning techniques, this chapter addresses the spatial complexity of these environments. The algorithm’s validation across diverse geographic and ecological settings ensures its applicability beyond the initial study sites. This advancement underscores the critical role of cutting-edge remote sensing technologies in ecological monitoring.

In Chapter 4, the methodology evolves to include red macroalgae, specifically targeting the invasive species Gracilaria vermiculophylla. By adapting the algorithm from Chapter 3, this study extends its application to a different taxonomic group, demonstrating the flexibility and scalability of the approach. Additionally, this chapter integrates LiDAR-based topographical data to examine the relationship between habitat characteristics and macroalgal distribution. The insights gained from mapping and modeling the spatial dynamics of G. vermiculophylla provide valuable implications for managing invasive species and conserving native biodiversity.

Finally, Chapter 5 examines the physiological impacts of environmental stressors, specifically marine and atmospheric heatwaves, on seagrass reflectance. Through controlled laboratory experiments and field validations, this chapter highlights the spectral responses of Zostera noltei under heatwave conditions. Well-established spectral indices such as the NDVI and GLI are employed, and a new index, the Seagrass Heat Shock Index (SHSI), is developed to specifically identify heatwave-impacted seagrasses. These indices provide metrics to detect and quantify stress-induced changes. These findings emphasize the role of remote sensing in assessing the resilience and vulnerability of intertidal ecosystems under climate change.

<!-- \chaptertitlepage{Chapter2/img/ASD_psd.png}{2}{Multi- and hyperspectral classification of soft-bottom intertidal vegetation using a spectral library for coastal biodiversity remote sensing}{Chapter2/img/Seagrass_quadrats_psd.png} -->

<!-- ::: {.content-visible} -->
<!-- \newpage -->
<!-- ::: -->


```{=latex}
\end{spacing}
```

```{=latex}
\renewcommand{\chaptertopimage}{Chapter2/img/ASD_psd.png}
\renewcommand{\chapterbottomimage}{Chapter2/img/Seagrass_quadrats_psd.png}
```

```{=latex}
\newpage\null\thispagestyle{empty}\newpage

```

